require'autocmd'
require'settings'
require'packer-setup'
require'plugins'
require'keybindings'
require'colorscheme'
require'plugins.nvimtree'
require'plugins.treesitter'
require'wallpaper'
require'plugins.telescope'
require'plugins.refactoring'
require'plugins.dap'
-- require'lsp'

